### ISSUE TITLE
[1.10.2-2.0.6.0-dev3] Welcome sound plays on world load & on world focus

### ISSUE THREAD

**Issue by Compegen** [Theray070696/mariodeath#10]
The world join sound currently will play twice when opening a world: When the world is loaded, and when it gains focus.

How to reproduce: Launch a world then before its done loading either alt-tab or click out of the Minecraft window. The sound will play when the world is done loading. Go back into Minecraft & continue into the world. The sound will then play a second time.

**Comment by Theray070696** [comment]
Caused by vanilla, can't fix
