### ISSUE TITLE
BiomeDecorator Crash

### ISSUE THREAD

**Issue by Gamerbolts** [Theray070696/mariodeath#12]
Hi, I am creating a modpack and was testing out mods and yours worked, the castles spawn, the sound in the beginning (can you add a config option to disable that btw). But when I tried to tp to the dimension, I crashed. I'm using the newest version for 1.12

https://pastebin.com/UscJAwGy

Any help is appreciated. Thank you!

**Comment by Theray070696** [comment]
The fix and the config option will be in a build tonight.
Thanks for the report! :)
