### ISSUE TITLE
[2.0.5.0] Pipes can be linked to already linked pipes

### ISSUE THREAD

**Issue by Compegen** [Theray070696/mariodeath#6]
Pipes can be linked to other pipes, but leave the previous part of the pair still linked.
_____
Causes the following behavior:
- A was linked to B
    - A went to B, B went to A
- A is now linked to C
    - A goes to C
    - C goes to A
    - B goes to A

**Comment by Theray070696** [comment]
I'm leaving this in. I don't care. That's amazing
